name: rhizopus-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13.3
  - numpy=2.2.5
  - pandas=2.2.3
  - matplotlib=3.10.1
  - matplotlib-venn=1.1.2
  - seaborn=0.13.2
  - scipy=1.15.2
  - scikit-learn=1.6.1
  - statsmodels=0.14.4
  - scikit-posthocs=0.11.4
  - statannotations=0.7.1
  - openpyxl=3.1.5
  - biopython=1.85
  - pyyaml=6.0.2
  - pyaml=25.1.0
  - pip